# Generated by Django 3.1 on 2020-11-19 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('Europe', (('PT', 'Portugal'), ('ES', 'Spain'), ('FR', 'France'), ('NL', 'The Netherlands'), ('EN', 'England'))), ('America', (('CA', 'Canada'), ('US', 'United States of America'), ('BR', 'Brazil'))), ('Africa', (('AL', 'Algeria'), ('AN', 'Angola'))), ('Asia', (('CH', 'China'), ('CM', 'Cambodia'), ('IN', 'India'), ('JA', 'Japan'))), ('Oceania', (('AU', 'Australia'), ('NZ', 'New Zealand'), ('PO', 'Polynesia')))], max_length=100)),
                ('door', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('wind', 'wind'), ('strings', 'strings'), ('percussion', 'percussion')], max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('nr_serie', models.CharField(max_length=20)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('whishlist', 'wishlist'), ('order', 'order'), ('shoppingcart', 'shoppingcart')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('Europe', (('PT', 'Portugal'), ('ES', 'Spain'), ('FR', 'France'), ('NL', 'The Netherlands'), ('EN', 'England'))), ('America', (('CA', 'Canada'), ('US', 'United States of America'), ('BR', 'Brazil'))), ('Africa', (('AL', 'Algeria'), ('AN', 'Angola'))), ('Asia', (('CH', 'China'), ('CM', 'Cambodia'), ('IN', 'India'), ('JA', 'Japan'))), ('Oceania', (('AU', 'Australia'), ('NZ', 'New Zealand'), ('PO', 'Polynesia')))], max_length=100)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Rather not say')], max_length=100)),
                ('contact', models.PositiveBigIntegerField()),
                ('role', models.CharField(choices=[('A', 'Admin'), ('S', 'Staff'), ('C', 'Customer')], max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_time', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('PROC', 'Processing order'), ('DELIV', 'Sent to delivery'), ('SENT', 'On its way'), ('REC', 'Delivered at the address')], max_length=100)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal')], max_length=20)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemlist')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
        ),
        migrations.AddField(
            model_name='itemlist',
            name='items',
            field=models.ManyToManyField(to='app.ItemQuantity'),
        ),
        migrations.AddField(
            model_name='itemlist',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.person'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.manufacturer'),
        ),
    ]
